name: diac_client
description: Dart based In-App Communication client :-) Easily display server-configured messages.
version: 0.1.0
homepage: https://github.com/hpoul/diac

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ">=1.8.0 <2.0.0"
  clock: ">=1.0.0 <2.0.0"
  freezed_annotation: ">=0.7.1 <1.0.0"
  json_annotation: ">=3.0.0 <5.0.0"
  http: ">=0.12.1 <1.0.0"
  logging: ">=0.11.0 <2.0.0"
  flutter_async_utils: ">=0.0.1 <1.0.0"
  rxdart: ">=0.24.0 <1.0.0"
  expressions: ">=0.1.5 <1.0.0"
  uuid: ">=2.0.0 <4.0.0"
  # for the bin/ dart file
  logging_appenders: ">=0.4.0 <2.0.0"

  ######################
  #### plugin dependencies (with native code)
  package_info: ">=0.4.0+18 <3.0.0"
  url_launcher: ">=5.4.7 <7.0.0"
  # (depends on path_provider)
  simple_json_persistence: ">=1.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  builder_static_text: ^0.0.1+2
  mockito: ^5.0.0
  fake_async: ^1.2.0
  plugin_platform_interface: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
