name: diac_client
description: Dart based In-App Communication client :-) Easily display server-configured messages.
version: 0.1.1
homepage: https://github.com/hpoul/diac
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  clock: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.5.0
  http: '>=0.13.3 <2.0.0'
  logging: '>=1.0.1 <2.0.0'
  flutter_async_utils: ^1.0.0+1
  rxdart: ^0.28.0
  expressions: #^0.2.3
    git:
      url: https://github.com/legacyofplay/expressions.git
      ref: 84192f4b8ac7e53889d2b980df62cc1cdbf47da7
  uuid: ">=4.0.0 <5.0.0"
  # for the bin/ dart file
  logging_appenders: ^1.2.0+1

  ######################
  #### plugin dependencies (with native code)
  package_info_plus: ">=4.0.0 <9.0.0"
  url_launcher: ^6.1.2
  # (depends on path_provider)
  simple_json_persistence: ^2.1.0+2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  mockito: ^5.2.0
  fake_async: ^1.3.0
  plugin_platform_interface: ^2.1.2
  flutter_lints: ^6.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
