name: diac_client
description: Dart based In-App Communication client :-) Easily display server-configured messages.
version: 0.1.0
homepage: https://github.com/hpoul/diac

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1
  clock: ^1.1.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  http: ^0.13.3
  logging: ^1.0.1
  flutter_async_utils: ^1.0.0-nullsafety.1
  rxdart: ^0.27.0
  expressions: ^0.2.0
  uuid: ^3.0.4
  # for the bin/ dart file
  logging_appenders: ^1.0.0

  ######################
  #### plugin dependencies (with native code)
  package_info_plus: ^1.0.3
  url_launcher: ^6.0.3
  # (depends on path_provider)
  simple_json_persistence: ^2.0.0-nullsafety.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  mockito: ^5.0.10
  fake_async: ^1.2.0
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^1.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
